### ISSUE TITLE
Revoke access

### ISSUE THREAD

**Issue by fyockm** [scttnlsn/mongoose-acl#8]
Trying to decide if there's any merit to creating an explicit `revokeAccess` method? 

Obviously, `setAccess` with empty (or no) perms could be called, effectively revoking access. However, it might be even better to go a step further and actually delete the key(s) instead of assigning an empty array?

For `object`, something like this:

```
    schema.methods.revokeAccess = function(key) {
        if (this[options.path]) {
            delete this[options.path][key];
            this.markModified(options.path);
        }
    };
```

On the `subject` side, it probably makes sense to have separate `revokeAccess` and `revokeAllAccess` methods - the former for just the main key, and the latter including additional and public keys.

Thoughts? I'd be happy to submit a PR with tests if you agree.

**Comment by scttnlsn** [comment]
Sounds like a good idea.  PR is definitely welcome!

**Comment by fyockm** [comment]
Sorry for the delay. I did the work for object (which was all I really needed), but didn't get around to doing the subject side. Submitting what I have now.

Updates to subject can be done in the future if someone wants or needs.
